az-configuration: []
iaas-configurations:
- iam_instance_profile: ''
  key_pair_name: ''
  name: default
  region: ''
  security_group: ''
  ssh_private_key: ''
network-assignment:
  network:
    name: infrastructure
  singleton_availability_zone:
    name: ''
networks-configuration:
  networks:
  - name: pas
    subnets: []
  - name: infrastructure
    subnets: []
  - name: services
    subnets: []
properties-configuration:
  director_configuration:
    ntp_servers_string: 169.254.169.123
    resurrector_enabled: true
  security_configuration:
    opsmanager_root_ca_trusted_certs: true
    trusted_certificates: ''
vmextensions-configuration:
- name: web-extension
  cloud_properties:
    lb_target_groups: []
    security_groups: []
- name: ssh-extension
  cloud_properties:
    lb_target_groups: []
    security_groups: []
- name: tcp-extension
  cloud_properties: 
    lb_target_groups: []
    security_groups: []