---
opsman-configuration:
  aws:
    region: ((region))
    vm_name: ((opsman-name))
    vpc_subnet_id: ((public-subnet-id))
    security_group_id: ((opsman-security-group))
    key_pair_name: ((opsman-keypair-name))
    iam_instance_profile_name: ((opsman-iam-profile))
    instance_type: r4.large
    public_ip: ((opsman-public-ip))
    use_instance_profile: true 